### ISSUE TITLE
Style in your stylesheet

### ISSUE THREAD

**Issue by cyouh95** [greghickman/TeaCozy#2]
It'd be a good idea to put all your styling in the stylesheet:

```css
.navigation a {
  color: white;
  ...
}
```

https://github.com/greghickman/TeaCozy/blob/master/index.html#L18-L20
https://github.com/greghickman/TeaCozy/blob/master/css/style.css#L74-L77
